name: holguin_taxi
description: Holguín Taxi - Release Candidate 1.3
publish_to: "none"
version: 1.3.0+4

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.0
  geolocator: ^14.0.3
  flutter_map: ^8.3.2
  latlong2: ^0.9.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
